server:
  port: 8801
spring:
  thymeleaf:
    cache: false # 修改页面实时生效，不缓存。注意：不用重启，但是要按Ctrl+F9重新编译一下项目才生效

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # 注：以下用于修改kafka topic名称，实际测试，必须放在application.yml里，不能放在bootstrap.yml里，否则无效
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: "newtopicname"  # 修改配置中心刷新用的kafka topic，默认是 springCloudBus
        springCloudBusOutput:
          destination: "newtopicname"  # 修改配置中心刷新用的kafka topic，默认是 springCloudBus

management:
  #server:
  #port: 7777 #不单独设置端口的话，和服务的端口一致
  #servlet:
  #context-path: /boot
  endpoints:
    web:
      exposure:
        include: "prometheus,info,health,refresh"   # 用*表示暴露全部
      #base-path: /    # 访问路径中没有actuator 直接是http://localhost:8080/Prometheus
  metrics:
    export:
      prometheus:
        enabled: true