server:
  port: 9003

spring:
  application:
    name: demo-mall

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka, http://localhost:9002/eureka