server:
  port: 8111
  servlet:
    context-path: /aws

spring:
  application:
    name: aws-s3-demo
  profiles:
    active: dev

aws-config:
  s3:
    access-key: abcd
    access-secret: 1234
    region: cn-north-1
    bucket: bucket-test
    down-url: https://bucket-test.s3.cn-north-1.amazonaws.com.cn
  lambda:
    access-key: abcd
    access-secret: 1234
    region: us-east-1
