server:
  port: 9001

spring:
  application:
    name: demo-eureka-server # 集群的name要相同

eureka:
  instance:
    appname: eureka1        # 实例的名称，必须不同
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka

#nohup java -Dserver.port=9001 -Deureka.instance.appname=eureka1 -Xms1024m -Xmx1024m -Xmn384m -XX:+UseConcMarkSweepGC -Deureka.client.service-url.defaultZone=http://localhost:9001/eureka,http://localhost:9002/eureka -jar /data/apps/eureka/demo-eureka1-0.0.1-SNAPSHOT.jar 2>&1 &
#nohup java -Dserver.port=9002 -Deureka.instance.appname=eureka2 -Xms1024m -Xmx1024m -Xmn384m -XX:+UseConcMarkSweepGC -Deureka.client.service-url.defaultZone=http://localhost:9001/eureka,http://localhost:9002/eureka -jar /data/apps/eureka/demo-eureka1-0.0.1-SNAPSHOT.jar 2>&1 &
