server:
  port: 8801

spring:
  application:
    name: spring-jpa-study
  profiles:
    active: dev

  jpa:
    show-sql: true  # 这个只会输出在控制台，不会记录到日志里
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

---  # 2个三横杠之间表示一个环境配置
spring:
  profiles: unittest # 单元测试，通过注解 ActiveProfiles 使用

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 实体与数据库不一致时，自动修改表结构
---
spring:
  profiles: dev # 开发使用这一段

  datasource:
    url: jdbc:mysql://10.2.0.163:3306/firstdemo?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: beinet
    password: beinet.cnbeinet.cn
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      initSQL: "SET NAMES utf8mb4"
    #      validation-query: "SELECT 1"
    #      validation-query-timeout: 10

    master:
      jdbc-url: jdbc:mysql://10.2.0.163:3306/demomaster?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: beinet
      password: beinet.cnbeinet.cn
    slave:
      url: jdbc:mysql://10.2.0.163:3306/demoslave?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: beinet
      password: beinet.cnbeinet.cn

    hikari:
      # 把maxLifetime设置为比数据库 wait-timeout较小的值，以避免问题：com.zaxxer.hikari.pool.PoolBase: HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1a751254 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
      max-lifetime: 40000  #单位毫秒，连接池里每个连接的最长生命周期，默认30分钟
      #      maximum-pool-size: 10  # 连接池最大连接数，默认10
      #      minimum-idle: 4        # 空闲超过idle-timeout的连接会被关闭，只保留4个不关闭；不推荐设置，让Hikari当成固定大小的连接池用
      #      idle-timeout: 40000    # 单位毫秒，空闲连接最大存活时间，默认10分钟，只有minimum-idle<maximum-pool-size时才生效
      #参考： https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
    druid:
#      test-while-idle: true
#      test-on-borrow: false
#      keep-alive: true
#      validation-query: "select 1"
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 100
      # 执行查询的超时时间（秒），未配置时使用query-timeout
      query-timeout: 5
      # 执行事务的超时时间（秒），未配置时使用query-timeout
      transaction-query-timeout: 5
      # 泄露的连接可以被删除的超时时间（秒）, 必须remove-abandoned为true才生效
      remove-abandoned-timeout: 1800
      remove-abandoned: false

  jpa:
    hibernate:
      ddl-auto: validate # 实体与数据库不一致时，报异常，不应当修改生产数据库，当然也不应该给权限
---