spring:
  application:
    name: cb-admin
  profiles:
    active: local
  cloud:
    config:
      profile: ${spring.profiles.active}
      label: ybltest
      client:
        skip-ssl-validation: true
  config:
    import: configserver:https://admin:admin@dev.benet.cn

management:
  #server:
  #port: 7777 #不单独设置端口的话，和服务的端口一致
  #servlet:
  #context-path: /boot
  endpoints:
    web:
      exposure:
        include: "*"   # 用*表示暴露全部
