spring:
  application:
    name: cb-admin
  profiles:
    active: local
  cloud:
    config:
      profile: ${spring.profiles.active}
      label: ybltest
      # client.skip-ssl-validation: true 这个配置无效
  config:
    import: configserver:http://localhost:8999

management:
  endpoints:
    web:
      exposure:
        include: "*"   # 用*表示暴露全部
